/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru;


import com.leon.ziru.model.ziru.tables.Advice;
import com.leon.ziru.model.ziru.tables.CrawlerErrorInfo;
import com.leon.ziru.model.ziru.tables.HelpPackage;
import com.leon.ziru.model.ziru.tables.Mission;
import com.leon.ziru.model.ziru.tables.User;
import com.leon.ziru.model.ziru.tables.records.AdviceRecord;
import com.leon.ziru.model.ziru.tables.records.CrawlerErrorInfoRecord;
import com.leon.ziru.model.ziru.tables.records.HelpPackageRecord;
import com.leon.ziru.model.ziru.tables.records.MissionRecord;
import com.leon.ziru.model.ziru.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AdviceRecord, Integer> IDENTITY_ADVICE = Identities0.IDENTITY_ADVICE;
    public static final Identity<CrawlerErrorInfoRecord, Integer> IDENTITY_CRAWLER_ERROR_INFO = Identities0.IDENTITY_CRAWLER_ERROR_INFO;
    public static final Identity<HelpPackageRecord, Integer> IDENTITY_HELP_PACKAGE = Identities0.IDENTITY_HELP_PACKAGE;
    public static final Identity<MissionRecord, Integer> IDENTITY_MISSION = Identities0.IDENTITY_MISSION;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdviceRecord> KEY_ADVICE_PRIMARY = UniqueKeys0.KEY_ADVICE_PRIMARY;
    public static final UniqueKey<CrawlerErrorInfoRecord> KEY_CRAWLER_ERROR_INFO_PRIMARY = UniqueKeys0.KEY_CRAWLER_ERROR_INFO_PRIMARY;
    public static final UniqueKey<HelpPackageRecord> KEY_HELP_PACKAGE_PRIMARY = UniqueKeys0.KEY_HELP_PACKAGE_PRIMARY;
    public static final UniqueKey<MissionRecord> KEY_MISSION_PRIMARY = UniqueKeys0.KEY_MISSION_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AdviceRecord, Integer> IDENTITY_ADVICE = createIdentity(Advice.ADVICE, Advice.ADVICE.ID);
        public static Identity<CrawlerErrorInfoRecord, Integer> IDENTITY_CRAWLER_ERROR_INFO = createIdentity(CrawlerErrorInfo.CRAWLER_ERROR_INFO, CrawlerErrorInfo.CRAWLER_ERROR_INFO.ID);
        public static Identity<HelpPackageRecord, Integer> IDENTITY_HELP_PACKAGE = createIdentity(HelpPackage.HELP_PACKAGE, HelpPackage.HELP_PACKAGE.ID);
        public static Identity<MissionRecord, Integer> IDENTITY_MISSION = createIdentity(Mission.MISSION, Mission.MISSION.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AdviceRecord> KEY_ADVICE_PRIMARY = createUniqueKey(Advice.ADVICE, "KEY_advice_PRIMARY", Advice.ADVICE.ID);
        public static final UniqueKey<CrawlerErrorInfoRecord> KEY_CRAWLER_ERROR_INFO_PRIMARY = createUniqueKey(CrawlerErrorInfo.CRAWLER_ERROR_INFO, "KEY_crawler_error_info_PRIMARY", CrawlerErrorInfo.CRAWLER_ERROR_INFO.ID);
        public static final UniqueKey<HelpPackageRecord> KEY_HELP_PACKAGE_PRIMARY = createUniqueKey(HelpPackage.HELP_PACKAGE, "KEY_help_package_PRIMARY", HelpPackage.HELP_PACKAGE.ID);
        public static final UniqueKey<MissionRecord> KEY_MISSION_PRIMARY = createUniqueKey(Mission.MISSION, "KEY_mission_PRIMARY", Mission.MISSION.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
