/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru;


import com.leon.ziru.model.ziru.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user</code>.
     */
    public static final User USER = com.leon.ziru.model.ziru.tables.User.USER;
}
