/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru;


import com.leon.ziru.model.ziru.tables.Advice;
import com.leon.ziru.model.ziru.tables.CrawlerErrorInfo;
import com.leon.ziru.model.ziru.tables.HelpPackage;
import com.leon.ziru.model.ziru.tables.Mission;
import com.leon.ziru.model.ziru.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>advice</code>.
     */
    public static final Advice ADVICE = com.leon.ziru.model.ziru.tables.Advice.ADVICE;

    /**
     * The table <code>crawler_error_info</code>.
     */
    public static final CrawlerErrorInfo CRAWLER_ERROR_INFO = com.leon.ziru.model.ziru.tables.CrawlerErrorInfo.CRAWLER_ERROR_INFO;

    /**
     * The table <code>help_package</code>.
     */
    public static final HelpPackage HELP_PACKAGE = com.leon.ziru.model.ziru.tables.HelpPackage.HELP_PACKAGE;

    /**
     * The table <code>mission</code>.
     */
    public static final Mission MISSION = com.leon.ziru.model.ziru.tables.Mission.MISSION;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = com.leon.ziru.model.ziru.tables.User.USER;
}
