/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.records;


import com.leon.ziru.model.ziru.tables.HomePageMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HomePageMessageRecord extends UpdatableRecordImpl<HomePageMessageRecord> implements Record5<Integer, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1686279432;

    /**
     * Setter for <code>home_page_message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>home_page_message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>home_page_message.json_content</code>.
     */
    public void setJsonContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>home_page_message.json_content</code>.
     */
    public String getJsonContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>home_page_message.enable</code>.
     */
    public void setEnable(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>home_page_message.enable</code>.
     */
    public Integer getEnable() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>home_page_message.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>home_page_message.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>home_page_message.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>home_page_message.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return HomePageMessage.HOME_PAGE_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HomePageMessage.HOME_PAGE_MESSAGE.JSON_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return HomePageMessage.HOME_PAGE_MESSAGE.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return HomePageMessage.HOME_PAGE_MESSAGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return HomePageMessage.HOME_PAGE_MESSAGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJsonContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJsonContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value2(String value) {
        setJsonContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value3(Integer value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HomePageMessageRecord
     */
    public HomePageMessageRecord() {
        super(HomePageMessage.HOME_PAGE_MESSAGE);
    }

    /**
     * Create a detached, initialised HomePageMessageRecord
     */
    public HomePageMessageRecord(Integer id, String jsonContent, Integer enable, Timestamp createTime, Timestamp updateTime) {
        super(HomePageMessage.HOME_PAGE_MESSAGE);

        set(0, id);
        set(1, jsonContent);
        set(2, enable);
        set(3, createTime);
        set(4, updateTime);
    }
}
