/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.records;


import com.leon.ziru.model.ziru.tables.HomePageMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HomePageMessageRecord extends UpdatableRecordImpl<HomePageMessageRecord> implements Record7<Integer, String, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1775386742;

    /**
     * Setter for <code>home_page_message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>home_page_message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>home_page_message.msg_p</code>.
     */
    public void setMsgP(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>home_page_message.msg_p</code>.
     */
    public String getMsgP() {
        return (String) get(1);
    }

    /**
     * Setter for <code>home_page_message.msg_a</code>.
     */
    public void setMsgA(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>home_page_message.msg_a</code>.
     */
    public String getMsgA() {
        return (String) get(2);
    }

    /**
     * Setter for <code>home_page_message.i_msg</code>.
     */
    public void setIMsg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>home_page_message.i_msg</code>.
     */
    public String getIMsg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>home_page_message.enable</code>.
     */
    public void setEnable(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>home_page_message.enable</code>.
     */
    public Integer getEnable() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>home_page_message.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>home_page_message.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>home_page_message.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>home_page_message.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return HomePageMessage.HOME_PAGE_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HomePageMessage.HOME_PAGE_MESSAGE.MSG_P;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return HomePageMessage.HOME_PAGE_MESSAGE.MSG_A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return HomePageMessage.HOME_PAGE_MESSAGE.I_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return HomePageMessage.HOME_PAGE_MESSAGE.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return HomePageMessage.HOME_PAGE_MESSAGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return HomePageMessage.HOME_PAGE_MESSAGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMsgP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMsgA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMsgP();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMsgA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value2(String value) {
        setMsgP(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value3(String value) {
        setMsgA(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value4(String value) {
        setIMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value5(Integer value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HomePageMessageRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HomePageMessageRecord
     */
    public HomePageMessageRecord() {
        super(HomePageMessage.HOME_PAGE_MESSAGE);
    }

    /**
     * Create a detached, initialised HomePageMessageRecord
     */
    public HomePageMessageRecord(Integer id, String msgP, String msgA, String iMsg, Integer enable, Timestamp createTime, Timestamp updateTime) {
        super(HomePageMessage.HOME_PAGE_MESSAGE);

        set(0, id);
        set(1, msgP);
        set(2, msgA);
        set(3, iMsg);
        set(4, enable);
        set(5, createTime);
        set(6, updateTime);
    }
}
