/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.records;


import com.leon.ziru.model.ziru.tables.Mission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionRecord extends UpdatableRecordImpl<MissionRecord> implements Record8<Integer, String, Integer, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1428101447;

    /**
     * Setter for <code>mission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mission.source_url</code>. 房源链接
     */
    public void setSourceUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mission.source_url</code>. 房源链接
     */
    public String getSourceUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mission.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mission.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mission.room_name</code>. 房源名称
     */
    public void setRoomName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mission.room_name</code>. 房源名称
     */
    public String getRoomName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mission.room_status</code>. 房屋状态
     */
    public void setRoomStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mission.room_status</code>. 房屋状态
     */
    public String getRoomStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mission.status</code>. 0 运行中 1 已停止
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mission.status</code>. 0 运行中 1 已停止
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mission.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mission.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mission.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mission.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Mission.MISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mission.MISSION.SOURCE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Mission.MISSION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mission.MISSION.ROOM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Mission.MISSION.ROOM_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Mission.MISSION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Mission.MISSION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Mission.MISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value2(String value) {
        setSourceUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value4(String value) {
        setRoomName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value5(String value) {
        setRoomStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Integer value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MissionRecord
     */
    public MissionRecord() {
        super(Mission.MISSION);
    }

    /**
     * Create a detached, initialised MissionRecord
     */
    public MissionRecord(Integer id, String sourceUrl, Integer userId, String roomName, String roomStatus, Integer status, Timestamp createTime, Timestamp updateTime) {
        super(Mission.MISSION);

        set(0, id);
        set(1, sourceUrl);
        set(2, userId);
        set(3, roomName);
        set(4, roomStatus);
        set(5, status);
        set(6, createTime);
        set(7, updateTime);
    }
}
