/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.records;


import com.leon.ziru.model.ziru.tables.Mission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionRecord extends UpdatableRecordImpl<MissionRecord> implements Record13<Integer, String, Integer, String, Integer, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2036081671;

    /**
     * Setter for <code>mission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mission.source_url</code>. 房源链接
     */
    public void setSourceUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mission.source_url</code>. 房源链接
     */
    public String getSourceUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mission.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mission.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mission.room_name</code>. 房源名称
     */
    public void setRoomName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mission.room_name</code>. 房源名称
     */
    public String getRoomName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mission.room_status</code>. 房屋状态
     */
    public void setRoomStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mission.room_status</code>. 房屋状态
     */
    public Integer getRoomStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mission.email</code>. 通知邮箱
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mission.email</code>. 通知邮箱
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mission.form_id</code>.
     */
    public void setFormId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mission.form_id</code>.
     */
    public String getFormId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mission.status</code>. -1 已删除 0 运行中 1 已停止
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>mission.status</code>. -1 已删除 0 运行中 1 已停止
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>mission.email_status</code>. 0 未发送邮件 1 已发送
     */
    public void setEmailStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mission.email_status</code>. 0 未发送邮件 1 已发送
     */
    public Integer getEmailStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mission.template_status</code>. 0 未发送模板 1 已发送
     */
    public void setTemplateStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>mission.template_status</code>. 0 未发送模板 1 已发送
     */
    public Integer getTemplateStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>mission.sms_status</code>. 0 未发送短信 1 已发送
     */
    public void setSmsStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mission.sms_status</code>. 0 未发送短信 1 已发送
     */
    public Integer getSmsStatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mission.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>mission.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>mission.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>mission.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, String, Integer, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, Integer, String, Integer, String, String, Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Mission.MISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mission.MISSION.SOURCE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Mission.MISSION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mission.MISSION.ROOM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Mission.MISSION.ROOM_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Mission.MISSION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Mission.MISSION.FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Mission.MISSION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Mission.MISSION.EMAIL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Mission.MISSION.TEMPLATE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Mission.MISSION.SMS_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Mission.MISSION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Mission.MISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getEmailStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getTemplateStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getSmsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getEmailStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getTemplateStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getSmsStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value2(String value) {
        setSourceUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value4(String value) {
        setRoomName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value5(Integer value) {
        setRoomStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value7(String value) {
        setFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value9(Integer value) {
        setEmailStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value10(Integer value) {
        setTemplateStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value11(Integer value) {
        setSmsStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value12(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value13(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, String value6, String value7, Integer value8, Integer value9, Integer value10, Integer value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MissionRecord
     */
    public MissionRecord() {
        super(Mission.MISSION);
    }

    /**
     * Create a detached, initialised MissionRecord
     */
    public MissionRecord(Integer id, String sourceUrl, Integer userId, String roomName, Integer roomStatus, String email, String formId, Integer status, Integer emailStatus, Integer templateStatus, Integer smsStatus, Timestamp createTime, Timestamp updateTime) {
        super(Mission.MISSION);

        set(0, id);
        set(1, sourceUrl);
        set(2, userId);
        set(3, roomName);
        set(4, roomStatus);
        set(5, email);
        set(6, formId);
        set(7, status);
        set(8, emailStatus);
        set(9, templateStatus);
        set(10, smsStatus);
        set(11, createTime);
        set(12, updateTime);
    }
}
