/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.records;


import com.leon.ziru.model.ziru.tables.Mission;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionRecord extends UpdatableRecordImpl<MissionRecord> implements Record17<Integer, String, Integer, String, Integer, String, String, Integer, Integer, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2007441878;

    /**
     * Setter for <code>mission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mission.source_url</code>. 房源链接
     */
    public void setSourceUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mission.source_url</code>. 房源链接
     */
    public String getSourceUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mission.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mission.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mission.room_name</code>. 房源名称
     */
    public void setRoomName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mission.room_name</code>. 房源名称
     */
    public String getRoomName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mission.bed_room_count</code>. 卧室数量
     */
    public void setBedRoomCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mission.bed_room_count</code>. 卧室数量
     */
    public Integer getBedRoomCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mission.room_no</code>. 卧室编号
     */
    public void setRoomNo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mission.room_no</code>. 卧室编号
     */
    public String getRoomNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mission.face</code>. 朝向
     */
    public void setFace(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mission.face</code>. 朝向
     */
    public String getFace() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mission.floor</code>. 层数
     */
    public void setFloor(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>mission.floor</code>. 层数
     */
    public Integer getFloor() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>mission.floor_total</code>. 总层数
     */
    public void setFloorTotal(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mission.floor_total</code>. 总层数
     */
    public Integer getFloorTotal() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mission.subway_primary</code>. 距地铁距离信息
     */
    public void setSubwayPrimary(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mission.subway_primary</code>. 距地铁距离信息
     */
    public String getSubwayPrimary() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mission.room_status</code>. 房屋状态
     */
    public void setRoomStatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>mission.room_status</code>. 房屋状态
     */
    public Integer getRoomStatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>mission.email</code>. 通知邮箱
     */
    public void setEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mission.email</code>. 通知邮箱
     */
    public String getEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mission.form_id</code>.
     */
    public void setFormId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mission.form_id</code>.
     */
    public String getFormId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mission.status</code>. -1 已删除 0 运行中 1 已停止
     */
    public void setStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>mission.status</code>. -1 已删除 0 运行中 1 已停止
     */
    public Integer getStatus() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>mission.email_status</code>. 0 未发送邮件 1 已发送
     */
    public void setEmailStatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>mission.email_status</code>. 0 未发送邮件 1 已发送
     */
    public Integer getEmailStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>mission.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>mission.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>mission.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>mission.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Integer, String, Integer, String, String, Integer, Integer, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Integer, String, Integer, String, String, Integer, Integer, String, Integer, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Mission.MISSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mission.MISSION.SOURCE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Mission.MISSION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mission.MISSION.ROOM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Mission.MISSION.BED_ROOM_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Mission.MISSION.ROOM_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Mission.MISSION.FACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Mission.MISSION.FLOOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Mission.MISSION.FLOOR_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Mission.MISSION.SUBWAY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Mission.MISSION.ROOM_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Mission.MISSION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Mission.MISSION.FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Mission.MISSION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Mission.MISSION.EMAIL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return Mission.MISSION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Mission.MISSION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getBedRoomCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getFloorTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSubwayPrimary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getEmailStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSourceUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getBedRoomCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRoomNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getFloorTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSubwayPrimary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getEmailStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value2(String value) {
        setSourceUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value4(String value) {
        setRoomName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value5(Integer value) {
        setBedRoomCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value6(String value) {
        setRoomNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value7(String value) {
        setFace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value8(Integer value) {
        setFloor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value9(Integer value) {
        setFloorTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value10(String value) {
        setSubwayPrimary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value11(Integer value) {
        setRoomStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value12(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value13(String value) {
        setFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value14(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value15(Integer value) {
        setEmailStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value16(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord value17(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, String value6, String value7, Integer value8, Integer value9, String value10, Integer value11, String value12, String value13, Integer value14, Integer value15, Timestamp value16, Timestamp value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MissionRecord
     */
    public MissionRecord() {
        super(Mission.MISSION);
    }

    /**
     * Create a detached, initialised MissionRecord
     */
    public MissionRecord(Integer id, String sourceUrl, Integer userId, String roomName, Integer bedRoomCount, String roomNo, String face, Integer floor, Integer floorTotal, String subwayPrimary, Integer roomStatus, String email, String formId, Integer status, Integer emailStatus, Timestamp createTime, Timestamp updateTime) {
        super(Mission.MISSION);

        set(0, id);
        set(1, sourceUrl);
        set(2, userId);
        set(3, roomName);
        set(4, bedRoomCount);
        set(5, roomNo);
        set(6, face);
        set(7, floor);
        set(8, floorTotal);
        set(9, subwayPrimary);
        set(10, roomStatus);
        set(11, email);
        set(12, formId);
        set(13, status);
        set(14, emailStatus);
        set(15, createTime);
        set(16, updateTime);
    }
}
