/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Advice implements Serializable {

    private static final long serialVersionUID = 845379348;

    private Integer   id;
    private String    content;
    private Integer   userId;
    private Timestamp createTime;
    private Timestamp updateTime;

    public Advice() {}

    public Advice(Advice value) {
        this.id = value.id;
        this.content = value.content;
        this.userId = value.userId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Advice(
        Integer   id,
        String    content,
        Integer   userId,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.content = content;
        this.userId = userId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Advice (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(userId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
