/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrawlerErrorInfo implements Serializable {

    private static final long serialVersionUID = -73293050;

    private Integer   id;
    private Integer   missionId;
    private Integer   errCount;
    private Integer   status;
    private Timestamp createTime;
    private Timestamp updateTime;

    public CrawlerErrorInfo() {}

    public CrawlerErrorInfo(CrawlerErrorInfo value) {
        this.id = value.id;
        this.missionId = value.missionId;
        this.errCount = value.errCount;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public CrawlerErrorInfo(
        Integer   id,
        Integer   missionId,
        Integer   errCount,
        Integer   status,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.missionId = missionId;
        this.errCount = errCount;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getMissionId() {
        return this.missionId;
    }

    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    public Integer getErrCount() {
        return this.errCount;
    }

    public void setErrCount(Integer errCount) {
        this.errCount = errCount;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CrawlerErrorInfo (");

        sb.append(id);
        sb.append(", ").append(missionId);
        sb.append(", ").append(errCount);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
