/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpPackage implements Serializable {

    private static final long serialVersionUID = 1571936055;

    private Integer   id;
    private Integer   missionId;
    private Integer   packageNum;
    private String    openId;
    private Timestamp createTime;
    private Timestamp updateTime;

    public HelpPackage() {}

    public HelpPackage(HelpPackage value) {
        this.id = value.id;
        this.missionId = value.missionId;
        this.packageNum = value.packageNum;
        this.openId = value.openId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public HelpPackage(
        Integer   id,
        Integer   missionId,
        Integer   packageNum,
        String    openId,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.missionId = missionId;
        this.packageNum = packageNum;
        this.openId = openId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getMissionId() {
        return this.missionId;
    }

    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    public Integer getPackageNum() {
        return this.packageNum;
    }

    public void setPackageNum(Integer packageNum) {
        this.packageNum = packageNum;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HelpPackage (");

        sb.append(id);
        sb.append(", ").append(missionId);
        sb.append(", ").append(packageNum);
        sb.append(", ").append(openId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
