/*
 * This file is generated by jOOQ.
*/
package com.leon.ziru.model.ziru.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -2121337846;

    private Integer   id;
    private String    phone;
    private String    nickName;
    private String    openId;
    private Integer   gender;
    private String    province;
    private String    city;
    private String    country;
    private Timestamp createTime;
    private Timestamp updateTime;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.phone = value.phone;
        this.nickName = value.nickName;
        this.openId = value.openId;
        this.gender = value.gender;
        this.province = value.province;
        this.city = value.city;
        this.country = value.country;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public User(
        Integer   id,
        String    phone,
        String    nickName,
        String    openId,
        Integer   gender,
        String    province,
        String    city,
        String    country,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.phone = phone;
        this.nickName = nickName;
        this.openId = openId;
        this.gender = gender;
        this.province = province;
        this.city = city;
        this.country = country;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(phone);
        sb.append(", ").append(nickName);
        sb.append(", ").append(openId);
        sb.append(", ").append(gender);
        sb.append(", ").append(province);
        sb.append(", ").append(city);
        sb.append(", ").append(country);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
